// <auto-generated />
using System;
using E_Posta_Gonderim_API.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Posta_Gonderim_API.Persistence.Migrations
{
    [DbContext(typeof(EPostaGonderimAPIDbContext))]
    partial class EPostaGonderimAPIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("E_Posta_Gonderim_API.Domain.Entities.KullaniciMailAdresi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Cinsiyet")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsYeri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailAdresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNumarasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unvan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KullanıcıMailAdresleri");
                });

            modelBuilder.Entity("E_Posta_Gonderim_API.Domain.Entities.KullaniciMailAdresi_YollananMail", b =>
                {
                    b.Property<int>("YollananMailId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciMailAdresiId")
                        .HasColumnType("int");

                    b.HasKey("YollananMailId", "KullaniciMailAdresiId");

                    b.HasIndex("KullaniciMailAdresiId");

                    b.ToTable("KullaniciMailAdresi_YollananMail");
                });

            modelBuilder.Entity("E_Posta_Gonderim_API.Domain.Entities.SirketMailAdresi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Host")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailAdresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PortNumarasi")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SirketMailAdresleri");
                });

            modelBuilder.Entity("E_Posta_Gonderim_API.Domain.Entities.YollananMail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Baslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mesaj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SirketMailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SirketMailId");

                    b.ToTable("YollananMailler");
                });

            modelBuilder.Entity("E_Posta_Gonderim_API.Domain.Entities.KullaniciMailAdresi_YollananMail", b =>
                {
                    b.HasOne("E_Posta_Gonderim_API.Domain.Entities.KullaniciMailAdresi", "KullaniciMailAdresi")
                        .WithMany("YollananMailler")
                        .HasForeignKey("KullaniciMailAdresiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Posta_Gonderim_API.Domain.Entities.YollananMail", "YollananMail")
                        .WithMany("KullaniciMailAdresleri")
                        .HasForeignKey("YollananMailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KullaniciMailAdresi");

                    b.Navigation("YollananMail");
                });

            modelBuilder.Entity("E_Posta_Gonderim_API.Domain.Entities.YollananMail", b =>
                {
                    b.HasOne("E_Posta_Gonderim_API.Domain.Entities.SirketMailAdresi", "SirketMailAdresleri")
                        .WithMany("YollananMailler")
                        .HasForeignKey("SirketMailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SirketMailAdresleri");
                });

            modelBuilder.Entity("E_Posta_Gonderim_API.Domain.Entities.KullaniciMailAdresi", b =>
                {
                    b.Navigation("YollananMailler");
                });

            modelBuilder.Entity("E_Posta_Gonderim_API.Domain.Entities.SirketMailAdresi", b =>
                {
                    b.Navigation("YollananMailler");
                });

            modelBuilder.Entity("E_Posta_Gonderim_API.Domain.Entities.YollananMail", b =>
                {
                    b.Navigation("KullaniciMailAdresleri");
                });
#pragma warning restore 612, 618
        }
    }
}
